### ISSUE TITLE
PiGPIO Initialisation Exception

### ISSUE THREAD

**Issue by CuriousJames** [CuriousJames/DIYAC#11]
Catch initialization exception of Pi GPIO.

Currently it dumps it's own message on screen, but this should be handled by our program and logged accordingly (then the program shutdown).

This is normally because the PiGPIO daemon is not running - so mention that in the logging.

I've been unable to work out how to catch the error at the initialization time (try does not catch it!) so we *MAY* have to do it on the next request to pi, but that is not ideal.

**Comment by tame-lx-tech** [comment]
sort of fixed - init function now tests whether pigpiod is running before pi=pigpio()
Test connection afterwards is still there.
