### ISSUE TITLE
Logger display output to be colourful

### ISSUE THREAD

**Issue by CuriousJames** [CuriousJames/DIYAC#13]
Black background, but foreground for the full line to be:

- DEBUG - White
- Info - Green
- WARN - Orange
- ERRR - Red

**Comment by CuriousJames** [comment]
Actually it will be set to this:
- DEBUG - White
- Info - Green
- WARN - Yellow
- ERRR - Red BACKGROUND, white Foreground

**Comment by CuriousJames** [comment]
Implemented, but may need adjusting

**Comment by tame-lx-tech** [comment]
fully implemented with above colour scheme
also fixed:
-colour escape strings don't go into log file
-python errors are normal colour, not the same colour as previous line
-better lookup system for colours
Did not implement proper term checking, so default is no colour. Can be enabled in settings, see settings_example
