### ISSUE TITLE
Bad load of settings not logged to file

### ISSUE THREAD

**Issue by CuriousJames** [CuriousJames/DIYAC#37]
If the settings file has bad JSON or can't be found nothing is written to the log file as it doesn't know where the log file exists, in this instance (lack of knowing where to log) it should assume the log file location is 'logFile' in 'log' folder in order to convey the issue to the user.

**Comment by tame-lx-tech** [comment]
This sort of error is logged to syslog and can also be picked up by systemd status.
New feature will push messages to systemd in the status by sdnotify
